//package com.redcarpetup.saveaccesstoken.model;
//
//import com.amazonaws.services.dynamodbv2.datamodeling.*;
//import lombok.Getter;
//import lombok.Setter;
//@Getter
//@Setter
//@DynamoDBTable(tableName = "access_token")
//public class Access_Token {
//
//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
//    private  Long id;
//    @DynamoDBAttribute
//    private String access_token;
//    @DynamoDBAttribute
//    private String expires_in;
//    @DynamoDBAttribute
//    private String refresh_token;
//    @DynamoDBAttribute
//    private String refresh_token_expires_in;
//    @DynamoDBAttribute
//    private String scope;
//    @DynamoDBAttribute
//    private String token_type;
//
//}
